### PR TITLE
Convert Adalo menu to floating menu

### PR DESCRIPTION
**Pull request by tylerssn**
The Adalo app bar in mobile previewer often pushes items off of screen that cannot be scrolled to because the screen does not account for the height of the app bar. This results in a different experience than one would encounter in production.

This PR converts the Adalo app bar to a floating, draggable icon. On first load, the icon animates to indicate to the user that it is draggable and clickable.

| App list screen | Repositioned Example 1 | Repositioned Example 2 | Navigation Options Example |
|-|-|-|-|
| image | image | image | image|

This PR introduces:

1. A new logo image
2. AppBar component code replaced with Animated `<Draggable/>` component from `react-native-draggable`
3. An additional prop called `hintDraggable` which will trigger the animation onload if true. This is currently set to true for the app list screen and false when the developer is viewing their adalo app.

### CODE REVIEW

**Comment by tylerssn** [comment]
The starting position may need to be moved down a bit or be wrapped in `Touchable` to ensure that the notification bar isn't activated when dragging downwards in some emulators.

**Comment by scott-massey** [comment]
I only see the new file here, are you sure you got all of the files?

**Comment by tylerssn** [comment]
> I only see the new file here, are you sure you got all of the files?

Strange. I'll update this later.

**Comment by tylerssn** [comment]
I had to manually move some of this stuff into the commit. Give it a try now.

**Review by scott-massey — APPROVED** [review]

**Comment by scott-massey** [comment]
A couple comments here:

- I don't think the draggable is showing up properly on iOS.
- We'll want to bump down where in the layout the app list starts so it doesn't go above the notch on iPhone devices.
- It looks like from your screenshots Android is working fine so I'm less worried about testing that.

**Comment by danicunhac** [comment]
Closing this PR as it's been inactive for a while

**Pull request closed without merging**
